/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import presentacion.Ventana;
import propiedades.*;

/**
 *
 * @author Fernando Flores
 */
public class ReglasPartida extends javax.swing.JFrame {
    public static Ventana ventana;
    /**
     * Creates new form ReglasPartida
     */
    public ReglasPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reglas = new javax.swing.JLabel();
        regla1 = new javax.swing.JLabel();
        regla2 = new javax.swing.JLabel();
        regla3 = new javax.swing.JLabel();
        regla4 = new javax.swing.JLabel();
        regla5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reglas.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        reglas.setForeground(new java.awt.Color(255, 255, 255));
        reglas.setText(Config.idioma.getProperty("valorReglasPartida"));
        getContentPane().add(reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 30));

        regla1.setBackground(new java.awt.Color(102, 0, 0));
        regla1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        regla1.setForeground(new java.awt.Color(255, 255, 255));
        regla1.setText(Config.idioma.getProperty("valorRegla1"));
        getContentPane().add(regla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 548, 65));

        regla2.setBackground(new java.awt.Color(153, 0, 0));
        regla2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        regla2.setForeground(new java.awt.Color(255, 255, 255));
        regla2.setText(Config.idioma.getProperty("valorRegla2"));
        getContentPane().add(regla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, 61));

        regla3.setBackground(new java.awt.Color(204, 0, 0));
        regla3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        regla3.setForeground(new java.awt.Color(255, 255, 255));
        regla3.setText(Config.idioma.getProperty("valorRegla3"));
        getContentPane().add(regla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 212, -1, 49));

        regla4.setBackground(new java.awt.Color(255, 0, 0));
        regla4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        regla4.setForeground(new java.awt.Color(255, 255, 255));
        regla4.setText(Config.idioma.getProperty("valorRegla4"));
        getContentPane().add(regla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 268, -1, 57));

        regla5.setBackground(new java.awt.Color(255, 102, 102));
        regla5.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        regla5.setForeground(new java.awt.Color(255, 255, 255));
        regla5.setText(Config.idioma.getProperty("valorRegla5"));
        getContentPane().add(regla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 332, -1, 51));

        jButton1.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIG4.jpg"))); // NOI18N
        jButton1.setText("Jugar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 90, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo negro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ventana = new Ventana(this);
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel regla1;
    private javax.swing.JLabel regla2;
    private javax.swing.JLabel regla3;
    private javax.swing.JLabel regla4;
    private javax.swing.JLabel regla5;
    private javax.swing.JLabel reglas;
    // End of variables declaration//GEN-END:variables
}
