/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import javax.swing.JFrame;
import menu.ConfiguracionDePartidaMultiPlayer;
import propiedades.Config;
import presentacion.TableroJuego;

/**
 *
 * @author Fernando Flores
 */
public class SelectorDeJuego extends javax.swing.JFrame {

    public static SelectorDeJuego sJuego;

    /**
     * Creates new form SelectorDeJuego
     */
    public SelectorDeJuego() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Comando para cerrar ventana cuando le das click a X.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModoJuego = new javax.swing.JLabel();
        unJugador = new javax.swing.JButton();
        multiJugador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModoJuego.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ModoJuego.setForeground(new java.awt.Color(255, 255, 255));
        ModoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIG4 3.jpg"))); // NOI18N
        ModoJuego.setText(Config.idioma.getProperty("valorModoJuego"));
        ModoJuego.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ModoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, -1));

        unJugador.setBackground(new java.awt.Color(0, 153, 153));
        unJugador.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        unJugador.setForeground(new java.awt.Color(255, 255, 255));
        unJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIG4 2.jpg"))); // NOI18N
        unJugador.setText(Config.idioma.getProperty("valorUnJugador"));
        unJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(unJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, 50));

        multiJugador.setBackground(new java.awt.Color(0, 102, 102));
        multiJugador.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        multiJugador.setForeground(new java.awt.Color(255, 255, 255));
        multiJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIG4 2.jpg"))); // NOI18N
        multiJugador.setText(Config.idioma.getProperty("valorMultiJugador"));
        multiJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(multiJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/810f56ca-5930-4665-9ee1-a734667c9bef.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unJugadorActionPerformed
        //Esto activa la pantalla un jugador
        ConfiguracionDePartidaSinglePlayer unJugador = new ConfiguracionDePartidaSinglePlayer();
        unJugador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_unJugadorActionPerformed

    private void multiJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiJugadorActionPerformed
        //Esto activa la pantalla multijugador
        ConfiguracionDePartidaMultiPlayer configuracion = new ConfiguracionDePartidaMultiPlayer();
        configuracion.setVisible(true);

        this.hide();
    }//GEN-LAST:event_multiJugadorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ModoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multiJugador;
    private javax.swing.JButton unJugador;
    // End of variables declaration//GEN-END:variables
}
